blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/twaclaw/mit-scheme-kernel/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/twaclaw/mit-scheme-kernel/blob/main/README.md
    about: Please check the documentation first.
