# If an alternative command, for instance `mechanics` is used to start the REPL,
# it can be specified here.
executable: mit-scheme

# mit-scheme outputs value as ';Value: <value>'. If filter_output is true,
# values are extracted from the output and returned as <value>
# the mit-scheme using the  Scmutils library, uses a different output format #|<value>|#
# see: https://groups.csail.mit.edu/mac/users/gjs/6946/mechanics-system-installation/native-code/installation.html

filter_output: true
output_value_regex: ^;Value:\s*(.+)$
#output_value_regex: ^\#\|\s*(.+)\s*\|\#$

# Check that the brackets in the code are balanced.
check_brackets_balance: true

# if an error occurs in the mit-scheme REPL, the following options can be used to
# automatically restart the REPL
auto_restart_on_error: false
restart_command: (RESTART 1)

# If a block of code of executed, mit-scheme outputs the results of all intermediate
# expressions. If return_only_last_output is true, only the last output is returned.
return_only_last_output: false
